// Generated by the protocol buffer compiler.  DO NOT EDIT!

package  com.net.core{

import com.netease.protobuf.Message;

import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class Msg extends Message {

//    public function Msg() {
//      registerField("svc","",Descriptor.ENUM,Descriptor.LABEL_OPTIONAL,1);
//      registerField("func","",Descriptor.STRING,Descriptor.LABEL_REQUIRED,2);
//      registerField("param","",Descriptor.INT32,Descriptor.LABEL_REPEATED,3);
//      registerField("buf","",Descriptor.STRING,Descriptor.LABEL_REPEATED,4);
//    }
    // optional .Msg.ServiceType svc = 1 [default = LOGIC_SERVICE];
//    public var svc:Number = -1; //No default value for now...
//
//    // required string func = 2;
//    public var func:String = "";
//
//    // repeated int32 param = 3;
//    public var param:Array = new Array();
//
//    // repeated string buf = 4;
//    public var buf:Array = new Array();
    
  
  }
}